blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blog/blogs/urls.py
"""определяет схемы URL для Blogs"""

from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    # домашняя страница
    path('', views.index, name='index'),
    # страница со списком всех тем
    path('topics/', views.topics, name='topics'),
    # страница с подробной информацией по отдельной теме
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # страница для добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),
    # страница для добавления новой записи
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # страница для редактирования записей
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

blog/users/urls.py
"""определяет схемы URL для пользователей"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
	# включить URL авторизации по умолчанию
	path('', include('django.contrib.auth.urls')),
	# страница регистрации
	path('register/', views.register, name='register'),
]

blog/blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
	"""тема, которую изучает пользователь"""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		"""возвращает строковое представление модели"""
		return self.text

class BlogPost(models.Model):
	"""темы блога"""
	topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		"""возвращает строковое представление модели"""
		if len(self.text) >= 50:
			return f"{self.text[:50]}..."
		else:
			return f"{self.text[:50]}"

blog/users/models.py
from django.db import models

# Create your models here.

blog/blogs/forms.py
from django import forms
from .models import Topic, BlogPost

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ['text']
		labels = {'text': ''}

class EntryForm(forms.ModelForm):
	class Meta:
		model = BlogPost
		fields = ['text']
		labels = {'text': 'BlogPost'}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blog/blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Topic, BlogPost 
from .forms import TopicForm, EntryForm
from django.http import Http404

# Create your views here.

def index(request):
	"""домашняя страница Blog"""
	return render(request, 'blogs/index.html')

@login_required
def topics(request):
	"""выводит список тем"""
	topics = Topic.objects.filter(owner=request.user).order_by('date_added')
	context = {'topics': topics}
	return render(request, 'blogs/topics.html', context)

@login_required
def topic(request, topic_id):
	"""выводит одну тему и все ее записи"""
	topic = Topic.objects.get(id=topic_id)
	# проверка того, что тема принадлежит текущему пользователю
	if topic.owner != request.user:
		raise Http404

	entries = topic.blogpost_set.order_by('-date_added')
	context = {'topic': topic, 'entries': entries}
	return render(request, 'blogs/topic.html', context)

@login_required
def new_topic(request):
	"""определяет новую тему"""
	if request.method != 'POST':
		# данные не отправлялись - создается пустая форма
		form = TopicForm()
	else:
		# отправлены данные POST, обработать данные
		form = TopicForm(data=request.POST)
		if form.is_valid():
			new_topic = form.save(commit=False)
			new_topic.owner = request.user
			new_topic.save()
			return redirect('blogs:topics')

	# вывести пустую или недействительную форму
	context = {'form': form}
	return render(request, 'blogs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
	"""добавляет новую запись по конкретной теме"""
	topic = Topic.objects.get(id=topic_id)
	if request.method != 'POST':
		# данные не отправлялись - создается пустая форма
		form = EntryForm()
	else:
		# отправлены данные POST, обработать данные
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return redirect('blogs:topic', topic_id=topic_id)

	# вывести пустую или недействительную форму
	context = {'topic': topic, 'form': form}
	return render(request, 'blogs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
	"""редактирует существующую запись"""
	entry = BlogPost.objects.get(id=entry_id)
	topic = entry.topic
	if topic.owner != request.user:
		raise Http404


	if request.method != 'POST':
		# исходный запрос, форма заполняется данными текущей записи
		form = EntryForm(instance=entry)
	else:
		# отправлены данные POST, обработать данные
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('blogs:topic', topic_id=topic.id)

	context = {'entry': entry, 'topic': topic, 'form': form}
	return render(request, 'blogs/edit_entry.html', context)

blog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
	"""регистрирует нового пользователя"""
	if request.method != 'POST':
		# выводит пустую форму регистрации
		form = UserCreationForm()
	else:
		# обработка заполненной формы
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			# выполнение входа и перенаправление на домашнюю страницу
			login(request, new_user)
			return redirect('blogs:index')

	# вывести пустую или недействительную форму
	context = {'form': form}
	return render(request, 'registration/register.html', context)

blog/blogs/templates/blogs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BLOG</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

      <a class="navbar-brand" href="{% url 'blogs:index' %}">BLOG</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarCollapse" aria-controls="navbarCollapse"
          aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blogs:topics' %}">Posts</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text"}">Hello, {{ user.username }}!</span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">Log out</a> 
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
            </li>
          {% endif %}
        </ul>
      </div>

    </nav>

    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main>

  </body>

</html>

blog/blogs/templates/blogs/edit_entry.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h3>Edit entry:<h3>
{% endblock page_header %}

{% block content %}

  <h2><a href="{% url 'blogs:topic' topic.id %}">{{ topic }}</a></h2>

  <form class="form" action="{% url 'blogs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'blogs:index' %}" />
  </form>

{% endblock content %}

blog/blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
  <div class='jumbotron'>
    <h1 class="display-3">My Blog helps you!!!</h1>

    <p class="lead">Make your own BLOG, and keep a list of the
        topics you're bloging about. Whenever you write something new
        about a topic, make an entry summarizing what you've wrote.</p>

    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a>
  </div>
{% endblock page_header %}

blog/blogs/templates/blogs/new_entry.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h3>Add a new POST:<h3>
{% endblock page_header %}

{% block content %}

  <h2><a href="{% url 'blogs:topic' topic.id %}">{{ topic }}</a></h2>
  
  <form class="form" action="{% url 'blogs:new_entry' topic.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Add POST</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'blogs:index' %}" />
  </form>

{% endblock content %}

blog/blogs/templates/blogs/new_topic.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Add a new topic:<h2>
{% endblock page_header %}

{% block content %}

<form method='post' action="{% url 'blogs:new_topic' %}" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button name="submit" class="btn btn-primary">Add topic</button>
  {% endbuttons %}

  <input type="hidden" name="next" value="{% url 'blogs:index' %}" /> 
</form>

{% endblock content %}

blog/blogs/templates/blogs/topic.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <h3>POST: {{ topic }}</h3>
{% endblock page_header %}

{% block content %}

  <p>
    <a href="{% url 'blogs:new_entry' topic.id %}">Add new entry</a>
  </p> 

  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a href="{% url 'blogs:edit_entry' entry.id %}">
            Edit entry</a></small>
      </h4>
      <div class="card-body">{{ entry.text|linebreaks }}</div>
    </div>
  {% empty %}
    <p>There are no entries for this POST yet.</p>
  {% endfor %}

{% endblock content %}

blog/blogs/templates/blogs/topics.html
{% extends "blogs/base.html" %}


{% block page_header %}
  <h1>POSTS</h1>
{% endblock page_header %}

{% block content %}
  <ul>
    {% for topic in topics %}
      <li><h3>
        <a href="{% url 'blogs:topic' topic.id %}">{{ topic }}</a>
      </h3></li>
    {% empty %}
      <li><h3>No posts have been added yet.</h3></li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'blogs:new_topic' %}">Add a new POST:</a></h3>

{% endblock content %}

  